import Head from 'next/head'
import Layout from '../components/Layout.js';
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Jae, Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainContainer}>
        <div className={styles.greetingContainer}>
          <p className={styles.greetingTxt}>Hello,</p>
          <p className={styles.greetingTxt}>Stranger!</p>
          <div className={styles.triangleContainer}>
            <div className={styles.outerTriangle}></div>
            <div className={styles.innerTriangle}></div>
          </div>
        </div>
      </main>
    </Layout>
  )
}
