import Head from 'next/head'
import Layout from '@/components/Layout';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Jae, Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div style={{height: '100%', padding: '4rem 4rem'}}>
          <p style={{fontFamily: 'amerton', fontSize: '5rem'}}>Hello,</p>
          <p style={{fontFamily: 'amerton', fontSize: '5rem'}}>Stranger!</p>
        </div>
      </main>
    </Layout>
  )
}
